name: Vesta
version: ${project.version}
main: gg.scenarios.vesta.Vesta
authors: [IAMRJ]
description: Vesta is the main server core for Scenarios.gg
website: https://scenarios.gg
depend: [ProtocolLib]
commands:
  message:
    aliases: [msg, m, tell, whisper]
  reply:
    aliases: [r]
  color:
    aliases: [username, settings]
  tags:
  tagadmin:
  gamemode:
    aliases: [gm]
  staffchat:
    aliases: [sc, mc]
  announce:
    aliases: [bc, broadcast]
  discord:
  hub: